name: CI

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint-test-smoke:
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"
          cache-dependency-path: |
            requirements.txt

      - name: Show Python version
        run: python --version

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          # CI helper deps (safe even if you don't use them yet)
          pip install pytest ruff

      - name: Prepare local config (if example exists)
        run: |
          if [ -f app_config_example.toml ] && [ ! -f app_config.toml ]; then
            cp app_config_example.toml app_config.toml
          fi

      - name: Lint (non-blocking for now)
        continue-on-error: true
        run: |
          # If no ruff config yet, this still works as a basic check
          ruff check . || true

      - name: Python syntax smoke check
        run: |
          python -m compileall -q .

      - name: App import / startup smoke test
        run: |
          python - <<'PY'
          import importlib
          import sys

          # Try app factory first (web/__init__.py)
          try:
              web = importlib.import_module("web")
              if hasattr(web, "create_app"):
                  app = web.create_app()
                  print("create_app() OK:", type(app).__name__)
              else:
                  print("No create_app() found in web package")
          except Exception as e:
              print("App factory smoke failed:", repr(e))
              # Fail here because startup path is important
              raise
          PY

      - name: Run tests (if present)
        run: |
          if [ -d tests ]; then
            pytest -q
          else
            echo "No tests/ directory yet - skipping pytest"
          fi