"""Structured schemas for LLM operations - generation and review."""

from __future__ import annotations

from dataclasses import dataclass, field
from typing import Any


# ==================== Common Result Models ====================

@dataclass
class LLMOperationStatus:
    """Status of an LLM operation."""
    success: bool
    error_message: str | None = None


@dataclass
class LLMOperationError:
    """Structured error from LLM operations."""
    code: str
    message: str
    details: dict[str, Any] = field(default_factory=dict)


@dataclass
class LLMStructuredParseResult[T]:
    """Result of parsing structured output from LLM."""
    success: bool
    data: T | None = None
    error: LLMOperationError | None = None
    raw_response: str | None = None


# ==================== Graph Generation Schemas ====================

@dataclass
class LLMGeneratedNode:
    """A node generated by LLM during graph generation."""
    id: str
    content: str
    summary: str = ""
    confidence: float = 1.0
    color: str = "#157f83"
    tags: list[str] = field(default_factory=list)
    evidence: list[str] = field(default_factory=list)


@dataclass
class LLMGeneratedConnection:
    """A connection generated by LLM during graph generation."""
    source_id: str
    target_id: str
    conn_type: str = "relates"
    description: str = ""
    strength: float = 1.0


@dataclass
class LLMGraphDraft:
    """Draft graph structure from LLM generation."""
    nodes: list[LLMGeneratedNode] = field(default_factory=list)
    connections: list[LLMGeneratedConnection] = field(default_factory=list)
    summary: str = ""


@dataclass
class LLMGraphGenerationResult:
    """Final result of graph generation pipeline."""
    status: LLMOperationStatus
    draft: LLMGraphDraft | None = None
    model: str = ""
    message: str = ""
    
    @property
    def enabled(self) -> bool:
        return self.status.success
    
    @property
    def node_count(self) -> int:
        return len(self.draft.nodes) if self.draft else 0
    
    @property
    def connection_count(self) -> int:
        return len(self.draft.connections) if self.draft else 0


# ==================== Graph Review Schemas ====================

@dataclass
class LLMGraphIssue:
    """An issue found during graph review (conflict or error)."""
    entity_type: str  # "node", "connection", "global"
    entity_id: str
    reason: str
    severity: str = "error"  # "error" | "warning"
    source: str = "rule"  # "rule" | "llm" | "merged"


@dataclass
class LLMGraphWarning:
    """A warning found during graph review."""
    entity_type: str
    entity_id: str
    reason: str
    suggestion: str = ""
    source: str = "rule"  # "rule" | "llm"


@dataclass
class LLMGraphReviewDraft:
    """Draft review result from LLM semantic analysis."""
    result: str = "OK"  # "OK" | "CONFLICT" | "WARNING"
    conflicts: list[LLMGraphIssue] = field(default_factory=list)
    warnings: list[LLMGraphWarning] = field(default_factory=list)
    overview: str = ""


@dataclass
class LLMGraphReviewAggregate:
    """Aggregated review result combining rule-based and LLM-based checks."""
    verdict: str = "OK"  # "OK" | "CONFLICT" | "WARNING"
    conflicts: list[LLMGraphIssue] = field(default_factory=list)
    warnings: list[LLMGraphWarning] = field(default_factory=list)
    overview: str = ""
    conflict_count: int = 0
    warning_count: int = 0
    reviewed_subgraph_scope: str | None = None  # For future subgraph review
    
    def to_dict(self) -> dict[str, Any]:
        """Convert to dictionary for API response."""
        return {
            "verdict": self.verdict,
            "conflicts": [
                {
                    "entity_type": c.entity_type,
                    "entity_id": c.entity_id,
                    "reason": c.reason,
                    "severity": c.severity,
                    "source": c.source,
                }
                for c in self.conflicts
            ],
            "warnings": [
                {
                    "entity_type": w.entity_type,
                    "entity_id": w.entity_id,
                    "reason": w.reason,
                    "suggestion": w.suggestion,
                    "source": w.source,
                }
                for w in self.warnings
            ],
            "overview": self.overview,
            "conflict_count": self.conflict_count,
            "warning_count": self.warning_count,
        }
